language: node_js
node_js: 10.13.0

bundler_args: "--jobs=4 --retry=3"
cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker-compose up -d
  - ./scripts/wait-for-it.sh 127.0.0.1:3000 -t 30
addons:
  chrome: stable

script:
- npm run lint
- npm run test:e2e:headless
# test should be run agains the docker ganache image but before arc.js
# allows for setting the contract address we need to test with a local ganache :(
- docker-compose down
- npm run ganacheDb
- npm run migrate-ganache
- npm run test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
