language: node_js
node_js: 10.13.0
addons:
  apt:
    update: true
bundler_args: "--jobs=4 --retry=3"

before_install:
  - sudo apt-get install -y libsecret-1-dev
addons:
  chrome: stable

script:
  - docker -v
  - docker-compose -v
  # fail on error
  # - set -e
  - echo 'docker-compose build' && echo -en 'travis_fold:start:script.1\\r'
  - docker-compose build

  - echo -en 'travis_fold:end:script.1\\r'
  - echo 'docker-compose up -d' && echo -en 'travis_fold:start:script.2\\r'
  - docker-compose up -d
  - echo -en 'travis_fold:end:script.2\\r'

  # wait for alchemy (the slowest latest process to respond
  - bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:3000)" != "200" ]]; do sleep 5; done'
  # prin the status of the services
  - npm run service-status

  # setup the environment
  - echo 'npm run setup-env' && echo -en 'travis_fold:start:script.4\\r'
  - npm run setup-env
  # move the migration.json file froms etup-env into the docker container
  - cp node_modules/@daostack/subgraph/migration.json config/
  - docker-compose exec alchemy /bin/bash -c "cp config/migration.json node_modules/@daostack/subgraph/"

  - echo -en 'travis_fold:end:script.4\\r'

  # get some diagnostic info fo debugging travis
  - echo 'Debug info:' && echo -en 'travis_fold:start:script.3\\r'
  - npm run service-status
  - wget -S -O - http://127.0.0.1:3000/
  - docker-compose logs alchemy
  - docker-compose logs ganache
  - docker-compose logs graph-node
  - echo -en 'travis_fold:end:script.3\\r'

  # check lint
  - npm run lint
  # run integration tests
  - npm run test:integration:headless
  # see if the app builds correctly
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
