language: node_js
node_js: 10.13.0

bundler_args: "--jobs=4 --retry=3"

before_install:
  - RUN apt-get update -y && apt-get install libsecret-1-dev -y
addons:
  chrome: stable

script:
  - docker-compose up -d
  - ./scripts/wait-for-it.sh 127.0.0.1:3000 -t 30
  # sleep for 30 seconds to give the docker container time to build the app
  - sleep 30
  - npm run lint
  - npm run test:e2e:headless
  # unit tests should be run in the docker container
  - docker-compose exec alchemy npm run test:unit

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
