language: node_js
node_js: 10.13.0

before_install:
- docker-compose up -d

script:
- npm run lint
- curl http://localhost:3000

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
