language: node_js
node_js: 9.5.0

before_script:
- npm run ganacheDb &>/dev/null & # run ganache in the backgroud

script:
- npm run lint
- npm run migrate-ganache
- npm run test
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
