language: node_js
node_js: 10.13.0
addons:
  apt:
    update: true
bundler_args: "--jobs=4 --retry=3"

before_install:
  - sudo apt-get install -y libsecret-1-dev
addons:
  chrome: stable

script:
  - echo 'docker-compose build' && echo -en 'travis_fold:start:script.1\\r'
  - docker-compose build
  - echo -en 'travis_fold:end:script.1\\r'
  - echo 'docker-compose up -d' && echo -en 'travis_fold:start:script.2\\r'
  - docker-compose up -d
  - echo -en 'travis_fold:end:script.2\\r'
  - ./scripts/wait-for-it.sh 127.0.0.1:8545 -t 30
    # setup the environment in the docker container (so migration.json is available)
  - echo 'npm run setup-env' && echo -en 'travis_fold:start:script.4\\r'
  - npm run setup-env
  - echo -en 'travis_fold:end:script.4\\r'

  # get some diagnostic info fo rdebubbing travis
  - echo 'Debug info:' && echo -en 'travis_fold:start:script.3\\r'
  - docker-compose exec alchemy pwd
  - docker-compose exec alchemy ls -l
  - docker-compose exec alchemy ls -l config
  - docker-compose logs alchemy
  - wget -S -O - http://127.0.0.1:3000/
  - npm run service-status
  - echo -en 'travis_fold:end:script.3\\r'
  #- sleep 5
  # - ./scripts/wait-for-it.sh 127.0.0.1:3000 -t 30
  # sleep for 30 seconds to give the docker container time to build the app
  # - sleep 20
  - npm run lint
  - npm run test:integration:headless
  # unit tests are run in the docker container
  # - docker-compose exec alchemy npm run test:unit
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
