language: node_js
node_js: 10.13.0
addons:
  apt:
    update: true
bundler_args: "--jobs=4 --retry=3"

before_install:
  - sudo apt-get install -y libsecret-1-dev curl
addons:
  chrome: stable

script:
  - docker -v
  - docker-compose -v
  # fail on error
  # - set -e
  - echo 'docker-compose build' && echo -en 'travis_fold:start:script.1\\r'
  - docker-compose build

  - echo -en 'travis_fold:end:script.1\\r'
  - echo 'docker-compose up -d' && echo -en 'travis_fold:start:script.2\\r'
  - docker-compose up -d
  - echo -en 'travis_fold:end:script.2\\r'

  # wait for alchemy (the slowest latest process to respond
  - bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' 127.0.0.1:3000)" != "200" ]]; do sleep 5; done'
  # prin the status of the services
  - npm run service-status

  # show the daos that are indexed
  - curl 'http://127.0.0.1:8000/subgraphs/name/daostack' -H 'Origin: http://127.0.0.1:8000' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: nl,it;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6,pt;q=0.5,es;q=0.4' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Referer: http://127.0.0.1:8000/subgraphs/name/daostack/graphql' -H 'Cookie: seen_disclaimer=true; seen_tour=true; io=9TnmcVwp4hrE5zgPAAAB' -H 'Connection: keep-alive' --data-binary '{"query":"  {daos { id }}","variables":null,"operationName":null}' --compressed
  - echo -en 'travis_fold:end:script.4\\r'

  # check lint
  - npm run lint
  # run integration tests
  - npm run test:integration:headless

  # get some diagnostic info fo debugging travis
  - echo 'Debug info:' && echo -en 'travis_fold:start:script.3\\r'
  - npm run service-status
  - docker-compose logs alchemy
  - docker-compose logs graph-node
  - echo -en 'travis_fold:end:script.3\\r'

  - curl 'http://127.0.0.1:8000/subgraphs/name/daostack' -H 'Origin: http://127.0.0.1:8000' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: nl,it;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6,pt;q=0.5,es;q=0.4' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Referer: http://127.0.0.1:8000/subgraphs/name/daostack/graphql' -H 'Cookie: seen_disclaimer=true; seen_tour=true; io=9TnmcVwp4hrE5zgPAAAB' -H 'Connection: keep-alive' --data-binary '{"query":"  {daos { id }}","variables":null,"operationName":null}' --compressed

  # see if the app builds correctly
  - npm run build-travis

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
