language: node_js
node_js: 9.5.0

before_script:
- docker-compose up

script:
- npm run lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
